# Prefix notation
number   : /-?[0-9]+(\.[0-9]+)?/ ;
operator : '+' | '-' | '*' | '/' | '%' | '^' | "min" | "max" ;
expr     : <number> | '(' <operator> <expr>+ ')' ;
lispy    : /^/ <operator> <expr>+ /$/ ;